# docker-compose.prod.yml
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./jac_video_frontend/Dockerfile.prod
      args:
        - NEXT_TELEMETRY_DISABLED=1
    image: jac_video_frontend:prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://localhost
      - NEXT_TELEMETRY_DISABLED=1
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - jac_video_network
    depends_on:
      - backend

  backend:
    build:
      context: ./jac_video_backend
      dockerfile: Dockerfile.prod
    image: jac_video_backend:prod
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - backend_static:/app/static
    environment:
      - ENV=production
    networks:
      - jac_video_network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  # Nginx服务用于反向代理和静态资源缓存
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - backend_static:/var/www/static
    depends_on:
      - frontend
      - backend
    networks:
      - jac_video_network
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  jac_video_network:
    driver: bridge
    # 添加自定义DNS配置
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  backend_static:  # 持久化静态文件存储 